config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :posts
  resources :destinies
  resources :travels
  resources :contacts
  resources :medicaments
  resources :diseases
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bloodtype.rb
class Bloodtype < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :country
  belongs_to :user
end

app/models/country.rb
class Country < ApplicationRecord
  belongs_to :language
end

app/models/destiny.rb
class Destiny < ApplicationRecord
  belongs_to :travel
  belongs_to :country
end

app/models/disease.rb
class Disease < ApplicationRecord
end

app/models/language.rb
class Language < ApplicationRecord
end

app/models/medicament.rb
class Medicament < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :travel
end

app/models/post_disease.rb
class PostDisease < ApplicationRecord
  belongs_to :post
  belongs_to :disease
end

app/models/post_medicament.rb
class PostMedicament < ApplicationRecord
  belongs_to :post
  belongs_to :medicament
end

app/models/travel.rb
class Travel < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  belongs_to :country
  belongs_to :bloodtype
  belongs_to :usertype
end

app/models/usertype.rb
class Usertype < ApplicationRecord
end

app/controllers/destinies_controller.rb
class DestiniesController < ApplicationController
  before_action :set_destiny, only: %i[ show edit update destroy ]

  # GET /destinies or /destinies.json
  def index
    @destinies = Destiny.all
  end

  # GET /destinies/1 or /destinies/1.json
  def show
  end

  # GET /destinies/new
  def new
    @destiny = Destiny.new
  end

  # GET /destinies/1/edit
  def edit
  end

  # POST /destinies or /destinies.json
  def create
    @destiny = Destiny.new(destiny_params)

    respond_to do |format|
      if @destiny.save
        format.html { redirect_to destiny_url(@destiny), notice: "Destiny was successfully created." }
        format.json { render :show, status: :created, location: @destiny }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @destiny.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /destinies/1 or /destinies/1.json
  def update
    respond_to do |format|
      if @destiny.update(destiny_params)
        format.html { redirect_to destiny_url(@destiny), notice: "Destiny was successfully updated." }
        format.json { render :show, status: :ok, location: @destiny }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @destiny.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /destinies/1 or /destinies/1.json
  def destroy
    @destiny.destroy!

    respond_to do |format|
      format.html { redirect_to destinies_url, notice: "Destiny was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_destiny
      @destiny = Destiny.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def destiny_params
      params.require(:destiny).permit(:name, :start_date, :finish_date, :travel_id, :country_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/destinies_helper.rb
module DestiniesHelper
end

app/helpers/diseases_helper.rb
module DiseasesHelper
end

app/helpers/medicaments_helper.rb
module MedicamentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/travels_helper.rb
module TravelsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/destinies/_destiny.html.erb
<div id="<%= dom_id destiny %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= destiny.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Start date:</strong>
    <%= destiny.start_date %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Finish date:</strong>
    <%= destiny.finish_date %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Travel:</strong>
    <%= destiny.travel_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Country:</strong>
    <%= destiny.country_id %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this destiny", destiny, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this destiny", edit_destiny_path(destiny), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/destinies/_form.html.erb
<%= form_with(model: destiny, class: "contents") do |form| %>
  <% if destiny.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(destiny.errors.count, "error") %> prohibited this destiny from being saved:</h2>

      <ul>
        <% destiny.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :start_date %>
    <%= form.date_field :start_date, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :finish_date %>
    <%= form.date_field :finish_date, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :travel_id %>
    <%= form.text_field :travel_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :country_id %>
    <%= form.text_field :country_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/destinies/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing destiny</h1>

  <%= render "form", destiny: @destiny %>

  <%= link_to "Show this destiny", @destiny, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to destinies", destinies_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/destinies/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Destinies</h1>
    <%= link_to "New destiny", new_destiny_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="destinies" class="min-w-full">
    <%= render @destinies %>
  </div>
</div>

app/views/destinies/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New destiny</h1>

  <%= render "form", destiny: @destiny %>

  <%= link_to "Back to destinies", destinies_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/destinies/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @destiny %>

    <%= link_to "Edit this destiny", edit_destiny_path(@destiny), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this destiny", destiny_path(@destiny), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to destinies", destinies_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>