config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :posts
  resources :destinies
  resources :travels
  resources :contacts
  resources :medicaments
  resources :diseases
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bloodtype.rb
class Bloodtype < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :country
  belongs_to :user
end

app/models/country.rb
class Country < ApplicationRecord
  belongs_to :language
end

app/models/destiny.rb
class Destiny < ApplicationRecord
  belongs_to :travel
  belongs_to :country
end

app/models/disease.rb
class Disease < ApplicationRecord
end

app/models/language.rb
class Language < ApplicationRecord
end

app/models/medicament.rb
class Medicament < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :travel
end

app/models/post_disease.rb
class PostDisease < ApplicationRecord
  belongs_to :post
  belongs_to :disease
end

app/models/post_medicament.rb
class PostMedicament < ApplicationRecord
  belongs_to :post
  belongs_to :medicament
end

app/models/travel.rb
class Travel < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  belongs_to :country
  belongs_to :bloodtype
  belongs_to :usertype
end

app/models/usertype.rb
class Usertype < ApplicationRecord
end

app/controllers/medicaments_controller.rb
class MedicamentsController < ApplicationController
  before_action :set_medicament, only: %i[ show edit update destroy ]

  # GET /medicaments or /medicaments.json
  def index
    @medicaments = Medicament.all
  end

  # GET /medicaments/1 or /medicaments/1.json
  def show
  end

  # GET /medicaments/new
  def new
    @medicament = Medicament.new
  end

  # GET /medicaments/1/edit
  def edit
  end

  # POST /medicaments or /medicaments.json
  def create
    @medicament = Medicament.new(medicament_params)

    respond_to do |format|
      if @medicament.save
        format.html { redirect_to medicament_url(@medicament), notice: "Medicament was successfully created." }
        format.json { render :show, status: :created, location: @medicament }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @medicament.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medicaments/1 or /medicaments/1.json
  def update
    respond_to do |format|
      if @medicament.update(medicament_params)
        format.html { redirect_to medicament_url(@medicament), notice: "Medicament was successfully updated." }
        format.json { render :show, status: :ok, location: @medicament }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @medicament.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medicaments/1 or /medicaments/1.json
  def destroy
    @medicament.destroy!

    respond_to do |format|
      format.html { redirect_to medicaments_url, notice: "Medicament was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medicament
      @medicament = Medicament.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def medicament_params
      params.require(:medicament).permit(:name, :compound)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/destinies_helper.rb
module DestiniesHelper
end

app/helpers/diseases_helper.rb
module DiseasesHelper
end

app/helpers/medicaments_helper.rb
module MedicamentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/travels_helper.rb
module TravelsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/medicaments/_form.html.erb
<%= form_with(model: medicament, class: "contents") do |form| %>
  <% if medicament.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(medicament.errors.count, "error") %> prohibited this medicament from being saved:</h2>

      <ul>
        <% medicament.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :compound %>
    <%= form.text_field :compound, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/medicaments/_medicament.html.erb
<div id="<%= dom_id medicament %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= medicament.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Compound:</strong>
    <%= medicament.compound %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this medicament", medicament, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this medicament", edit_medicament_path(medicament), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/medicaments/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing medicament</h1>

  <%= render "form", medicament: @medicament %>

  <%= link_to "Show this medicament", @medicament, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to medicaments", medicaments_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/medicaments/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Medicaments</h1>
    <%= link_to "New medicament", new_medicament_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="medicaments" class="min-w-full">
    <%= render @medicaments %>
  </div>
</div>

app/views/medicaments/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New medicament</h1>

  <%= render "form", medicament: @medicament %>

  <%= link_to "Back to medicaments", medicaments_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/medicaments/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @medicament %>

    <%= link_to "Edit this medicament", edit_medicament_path(@medicament), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this medicament", medicament_path(@medicament), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to medicaments", medicaments_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>